name: Deploy to A2 Hosting
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.A2_SSH_KEY }}

      - name: Deploy files
        run: |
          scp -r -o StrictHostKeyChecking=no -P ${{ secrets.A2_PORT }} \
          ./ ${{ secrets.A2_USER }}@${{ secrets.A2_HOST }}:${{ secrets.A2_PATH }}
